name: Deploy to VPS

on:
  push:
    branches: [main] # atau branch yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.nvm/nvm.sh
            cd /root/alkindivv.site
            git pull origin main
            nvm install 18
            nvm use 18
            npm install
            npm run build
            pm2 restart alkindivv-site
